### ISSUE TITLE
Prevent vertical scrolling on touch/drag

### ISSUE THREAD

**Issue by senner007** [darsain/sly#76]
The user experience is greatly improved if the vertical scrolling is locked when you swipe / drag/ touch horizontally. It is frustrating that the page is moving unintentionally.

It is for instance done when using hammer.js 
see drag_block_horizontal: true

Not so much an issue, but you did say that you needed help testing the mobile issues.

**Comment by stathes** [comment]
Was searching for the same thing as my man. 

Your plugin is epic!! Years after it's creation it's still better than anything I can find. Props! 

Horizontal scroll is really catching on now...

Thing is, it does not do what you are saying in this thread.

When I am on Google or any horizontal scroll I see in the wild, it always has horizontal locked. It's impossible to move both in the same motion.

However, on my application, I can start the scroll and then move my thumb in an almost circular motion clockwise..

What happens is both scrolls work. Horizontal inside, as well as the page as a whole goes up and down. I'm on a Google pixel, not an iPad.

It would be SUPER epic for a solution here. Personally I think default behavior should be locked.

Again, I know you are claiming this is the case already, but as an observant front end it does not lock...

That same observance however is what lead me to your plugin and this issue. 

I am sure I could hack my way to solving but since you know the architecture I figure I'd ask you first.

Thanks man, you rock
